<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClinicalAppointmentSystem.Domain\ClinicalAppointmentSystem.Domain.csproj" />
  </ItemGroup>

</Project>
